### ISSUE TITLE
Networking 1.1: To-Do List

### ISSUE THREAD

**Issue by LutzBlox** [LutzBlox/Networking#1]
- <strong>Add completed items under 'Completed' and work-in-progress items under 'In Progress'</strong>
<h2>IN PROGRESS</h2>
- <i>No items currently in progress!</i>
<h2>COMPLETED</h2>
- [x] Allow timeouts on server packet receiving.  (i.e. if  packet is not received in x amount of time, the socket does something)
- [x] Switch to Gradle
- [x] Add Travis builds for OpenJDK 7 just to be safe
- [x] Track pings (record pings per second).  Calculate this data in the connection itself so it can be retrieved from both ends.
- [x] Create safeties for clients/servers to catch null connections having methods called (maybe instead of having the Connection set to null have it set to a connection returned by <code>Connection.getUninitializedConnection()</code> that calls a private no-parameter constructor that defaults all values to 0, -1, "null", etc. but does not initialize the listener)
- [x] Add static method to retrieve IP of machine in Connection
- [x] Update <code>CHANGELOG.txt</code> so it includes all recent additions
- [x] Remove support in ExtendedMap for Null wrappers.  Make put() method check for actual nulls and throw an exception, but handle all Null wrapping in the classes that use ExtendedMap
- [x] Add a ConstantPingClient (or something like that) that is always sending and receiving packets.  If the program wants to send data, it can simply be merged with an existing packet.  The receive methods of the client's listener will only be called when the packets contain data (i.e. the remote program sent something).  Otherwise, these packets will only serve to maintain communication and ping time.  Timeouts will be very important with this type of client/server (because they are always sending, any timeouts are caused by problems with connections, not simply having nothing to send)
