### ISSUE TITLE
Networking 1.2.0: To-Do List

### ISSUE THREAD

**Issue by LutzBlox** [LutzBlox/Networking#2]
- <strong>Add completed items under 'Completed' and work-in-progress items under 'In Progress'</strong>
<h2>IN PROGRESS</h2>
- <i>Release complete!</i>
<h2>COMPLETED</h2>
- [x] Add <code>Query</code> system where a client can request certain data from the server, such as connected IPs, etc.  The server decides whether or not to send the packet (set <code>setQueryPolicy(QueryType type, QueryPolicy policy)</code>, for example: <code>server.setQueryPolicy(QueryType.CONNECTED_IPS, QueryPolicy.getRejectionPolicy("Unsafe information"));</code>).    Queries would be sent with another method, such as <code>query(QueryType type)</code> (i.e. <code>client.query(QueryType.CONNECTED_IPS);</code>).  Said method would return a Query object, and this object can be used to obtain resulting values and check the status.  Methods would include <code>getStatus()</code>, which would return a QueryStatus, <code>getResult()</code>, which would return the resulting value (or null/exception when rejected), etc.  <code>getStatus()</code> will return <code>QueryStatus.WORKING</code> when waiting for a response, but <code>QueryStatus.SUCCESSFUL</code> or <code>QueryStatus.REJECTED</code> when complete.  If the Connection times out while waiting for a response, the status will become <code>QueryStatus.TIMED_OUT</code>.  This method should be checked in a loop.  Each Query will have its own ID, starting at zero and increasing from there.  Packet data will look like <code>QRY:query:012345=connectedips</code>.  When Queries finish, their IDs are returned to a reusable pool of unused IDs, so if the max ID is taken, some can be reused.  If no IDs are in the reusable pool, an automatic rejection will occur, with a message like <code>Too many existing queries!</code>.  Servers can set how many queries they want from a client at any one time; this will be passed over on connection.
- [x] Investigate reason behind more consistent errors in SendReceiveTest.&nbsp;&nbsp;<strong>Changed <code>localhost</code> to <code>0.0.0.0</code>, but it is a Travis CI issue as it works perfectly on any other system.</strong>
- [x] Make error messages customizable and incorporate all error messages into a single class where they can be called with <code>Errors.noConnection()</code> or something like that
- [x] Update localization file to have default.properties with default (en_US) properties and comments on how to build your own localization files
- [x] Add encrypted packet support
- [x] Add localization for other error types
- [x] Remove DatabaseClient/Server (deprecated) because they aren't secure
- [x] Add a check to see if encryption key is null before using it (allows for more informative errors)
- [x] Allow a Connection to have an encryption status.  For instance, if the developer wants to encrypt every packet that travels across that connection, set the Connection's encryption status, which overrides any settings in the individual Packets (i.e. <code>client.getConnection().setEncrypted(true);</code>).  Servers may need to be done in through the Server class itself or a class that represents a group of connections (i.e. <code>ConnectionBundle</code>, etc.).  This would then be returned by <code>server.getConnections()</code>.  This object could then be utilized to alter all connections at once.
- [x] Find a memorable name for the library other than "Networking" or "__'s Networking Library".  <strong>LutzBlox's Simplified Networking Library (LSNL for short)</strong>
- [x] Send more server info on first packet by default (including name, max connection state, etc.)
- [x] Change README from having usage instructions to build instructions and move usage instructions (and update them) to the wiki pages
- [x] Update changelog
- [x] Correct Connection so it checks for a policy before actually trying to use it (prevents <code>NullPointerExceptions</code>)
- [x] Change Query codes so that default codes don't interfere with added ones (i.e. use "net-default:num_connected" rather than "num_connected", so if a developer wants to add a "num_connected" query, it won't interfere with the default)
- [x] Add wiki for tutorials/examples
- [x] Finish Javadoc for methods that override core JDK methods (close(), flush(), etc.)
